version: '2'

services:

  live.service:
    image: live.service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    volumes:
      - ../:/go/src/live-service
    environment:
      - domain=${DOMAIN}
      - mysql_host=${MYSQL_HOST}
      - mysql_port=${MYSQL_PORT}
      - mysql_database=${MYSQL_DATABASE}
      - mysql_user=${MYSQL_USER}
      - mysql_password=${MYSQL_PASSWORD}
      - mysql_table_prefix=t_
      - redis_host=${REDIS_HOST}
      - redis_port=${REDIS_PORT}
      - cache_driver=${CACHE_DRIVER}
      - oss_access_id=${OSS_ACCESS_ID}
      - oss_access_key=${OSS_ACCESS_KEY}
      - oss_end_point=${OSS_END_POINT}
      - oss_end_point_internal=${OSS_END_POINT_INTERNAL}
      - oss_bucket_name=${OSS_BUCKET_NAME}
      - root_path=${ROOT_PATH}
      - default_storage=${DEFAULT_STORAGE}
    depends_on:
      - redis-server
    links:
      - redis-server:redis-server

  # Web Server
  agent.live.service:
    image: daocloud.io/nginx
    volumes:
      - ./live-service.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - live.service
    links:
      - live.service:live.service

  # Cache Service
  redis-server:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - /data/redis/live:/data